#! /bin/sh

#  
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#                                               
#  https://github.com/baskerville/bspwm
#

bspc monitor -d 0 1 2 3 4 

bspc config border_width          1
bspc config window_gap            -1
bspc config top_padding           0
bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true 
bspc config focus_follows_pointer true

bspc rule -a feh state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled

killall -w sxhkd compton &
sleep 0.1
compton --config ~/.config/compton/bspcompton.conf &
feh --bg-fill --no-fehbg --randomize ~/Images &
sxhkd -c ~/.config/sxhkd/bspsxhkdrc &
xinput --set-prop 11 297 -0.8
bspwm
